### ISSUE TITLE
unable to parse valid Bibtex

### ISSUE THREAD

**Issue by AizazZaidee** [BERef/BibTeXLibrary#1]
@Article{pmid31201394,
   Author="Raza, S.  and Bangash, A. A.  and Ahmad, T. I.  and Khan, M. S. ",
   Title="{{P}ulmonary health risks of working at a cement plant in {K}hyber {P}akhtunkhwa province of {P}akistan}",
   Journal="J Pak Med Assoc",
   Year="2019",
   Volume="69",
   Number="6",
   Pages="869--873",
   Month="Jun",
   Abstract={To examine the risk and preventive factors of working in a cement plant.\\ The cross-sectional study was conducted from July to September, 2016, at a leading cement manufacturing plant in the Khyber Pakhtunkhwa province of Pakistan. An interviewer-administered questionnaire was used to collect data about the characteristics of exposed and unexposed subjects. The characteristics and occupational illnesses were compared between exposed and unexposed workers. Logistic regression was applied to estimate the odds ratio for risk and preventive factors associated with pulmonary illnesses linked with the profession.\\ Of the 550 workers contacted, 260(47.3%) agreed to participate. The mean age of the sample was 30.48}6.13 years. Of the total, 80(31%) were exposed and 180(69%) were unexposed. Overall, 96(37%) workers had medical coverage facility, while 114(63%) reported very good health. All socioeconomic and working characteristics were highly significant between exposed and unexposed workers (p<0.05). There were 67(25.7%) workers with pulmonary illnesses and the difference between the exposed and unexposed groups were significant (p<0.05).\\ Pulmonary health among workers could be improved by implementing occupational health improving strategies..},
   Note={[PubMed:\href{https://www.ncbi.nlm.nih.gov/pubmed/31201394}{31201394}] }
}

**Comment by JamesBradyBear** [comment]
Please see the pull request.

**Comment by AizazZaidee** [comment]
Please see the pull request with the issues fixed

**Comment by Blueve** [comment]
> Abstract=`{`To examine the risk and preventive factors of working in a cement plant.\ The cross-sectional study was conducted from July to September, 2016, at a leading cement manufacturing plant in the Khyber Pakhtunkhwa province of Pakistan. An interviewer-administered questionnaire was used to collect data about the characteristics of exposed and unexposed subjects. The characteristics and occupational illnesses were compared between exposed and unexposed workers. Logistic regression was applied to estimate the odds ratio for risk and preventive factors associated with pulmonary illnesses linked with the profession.\ Of the 550 workers contacted, 260(47.3%) agreed to participate. The mean age of the sample was 30.48`}`6.13 years. Of the total, 80(31%) were exposed and 180(69%) were unexposed. Overall, 96(37%) workers had medical coverage facility, while 114(63%) reported very good health. All socioeconomic and working characteristics were highly significant between exposed and unexposed workers (p<0.05). There were 67(25.7%) workers with pulmonary illnesses and the difference between the exposed and unexposed groups were significant (p<0.05).\ Pulmonary health among workers could be improved by implementing occupational health improving strategies..`}`

There are one `{` and two `}` which cause the braces cannot be closed.
